### ISSUE TITLE
Authorize by Lambda requires duplicated deployment of the authorizing function

### ISSUE THREAD

**Issue by horyd** [e-e-e/serverless-plugin-multi#4]
If you have an authorizing function shared across your app then it needs to be listed in each service.yml and the references to it from within that service.yml need to be namespaced in order for it to find the function. The following code works but is a bit yucky
```yaml
functions:
  authorize:
    handler: src/authorize.handler
  get:
    handler: src/surveys.get
    events:
      - http:
          path: /
          method: get
          cors: ${self:custom.cors}
          authorizer: surveys-authorize
  post:
    handler: src/surveys.post
    events:
      - http:
          path: /
          method: post
          cors: ${self:custom.cors}
          authorizer: surveys-authorize
```

**Comment by horyd** [comment]
Ok so above is the setup required for it to work with serverless-offline, but the below is what is required for `package`
```yml
functions:
  authorize:
    handler: src/authorize.handler
  get:
    handler: src/surveys.get
    events:
      - http:
          path: /
          method: get
          cors: ${self:custom.cors}
          authorizer: authorize
  post:
    handler: src/surveys.post
    events:
      - http:
          path: /
          method: post
          cors: ${self:custom.cors}
          authorizer: authorize
```

Quite odd!
